project:
  type: website
  output-dir: docs

website:
  title: "Metagenomics_Online"
  page-navigation: true
  bread-crumbs: false  
  favicon: /images/bacteria_icon.png
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - section: "**Setting Up on Galaxy**"
        contents: 
          - about.qmd
          - copy_datasets.qmd
          - inspect_sequences.qmd
      - section: "**Quality Control**"
        contents: 
          - href: fastq.qmd
          - href: fastqc.qmd
          - href: fastqc_results.qmd
          - href: fastqc_thegraphs.qmd
          - href: multiqc.qmd
          - href: multiqc_thegraphs.qmd
      - section: "**Preprocessing the reads**"
        contents: 
          - href: Why_preprocess.qmd
          - section: "**Illumina read processing**"
            contents:
            - href: CutAdapt.qmd
            - href: BBmerge.qmd
            - href: FastQGroomer.qmd 
            - href: QC_after_processing.qmd 
          - section: "**Nanopore read processing**"
            contents: 
            - href: Porechop.qmd
            - href: Fastp.qmd
      - section: "**Classifying Taxonomy**"
        contents: 
          - href: Classifications_overview.qmd 
          - href: kraken2.qmd
          - href: Bracken.qmd
          - href: Krakentools.qmd
          - href: KronaPieChart.qmd
          - href: kronapiechart_results.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



